### ISSUE TITLE
How to set touchable component ?

### ISSUE THREAD

**Issue by Kumar2971** [WrathChaos/react-native-duo-toggle-switch#115]
How to swap the button color as per password condition?

**Comment by Kumar2971** [comment]
A button color swap as per password validation how to do that ?

**Comment by Kumar2971** [comment]
How to disabled onpress event?or set active opacity for that button?

**Comment by WrathChaos** [comment]
https://github.com/WrathChaos/react-native-duo-toggle-switch/blob/master/lib/DuoToggleSwitch.tsx#L93

as you can see it takes the all of the props depends on the `TouchableComponent` and since TouchableComponent can be any Pressable component. It depends on your business logic. 

This does not limited by the library itself
